/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ShelfManager;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        System.out.println("Markus macht nen 960");

        System.out.println("Gruﬂ von Markus");
        System.out.print("Hallo");
        System.out.print("HalliHallo");

    }
}
